name: minify
run-name: Minify JS/CSS/HTML [gh-pages branch]

on:
  push:
    branches:
      - 'feat/minify'

jobs:
  checkout-minify-push:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4

      # Install NodeJS and CLI tools
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g terser
      - run: npm install -g csso-cli
      - run: npm install -g html-minifier

      # Perform minification, overwriting original files
      - run: terser ./js/tv.js --compress --mangle -o ./js/tv.js
      - run: csso ./css/tv.css -o ./css/tv.css
      - run: html-minifier --collapse-boolean-attributes --collapse-whitespace --minify-css --minify-js --minify-urls --remove-attribute-quotes --remove-comments --remove-empty-attributes --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes --remove-tag-whitespace --use-short-doctype -o index.html index.html

      # (Force) push changes to `gh-pages` branch
      - run: |
          git pull
          git config user.name manaracekom
          git config user.email manaraceko.manoppo@user.noreply.github.com
          git commit -am 'Automated minify of ${{ github.sha }}'
          git push --force -u origin gh-pages
