name: Robot Pengacak Ryan

on:
  push:
    branches:
      - eksperimen-ryan

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 1. Mengambil File Master
        uses: actions/checkout@v4

      - name: 2. Menyiapkan Mesin Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 3. Menginstall Alat Minifikasi Total
        run: npm install html-minifier-terser

      - name: 4. Membuat Skrip Pengeksekusi
        run: |
          cat << 'EOF' > run_obfuscator.js
          const fs = require('fs');
          const { minify } = require('html-minifier-terser');

          const files = ['control.html', 'daftar.html', 'index.html', 'overlay.html', 'tv.html', 'wasit.html'];

          async function processFiles() {
            for (let file of files) {
              if (fs.existsSync(file)) {
                let html = fs.readFileSync(file, 'utf8');
                
                try {
                  let resultHtml = await minify(html, {
                    collapseWhitespace: true,
                    removeComments: true,
                    minifyCSS: true,
                    minifyJS: {
                      compress: { drop_console: true },
                      mangle: { keep_fnames: true },
                      format: { comments: false }
                    }
                  });
                  
                  fs.writeFileSync(file, resultHtml);
                  console.log(`Berhasil memadatkan HTML, CSS, & JS pada: ${file}`);
                } catch (e) {
                  console.error("Gagal compress file " + file, e);
                }
              }
            }
          }
          processFiles();
          EOF

      - name: 5. Mulai Menggiling Kode Total
        run: node run_obfuscator.js

      - name: 6. Membersihkan Mesin dan Kotak Perkakas
        run: |
          rm run_obfuscator.js
          rm -rf node_modules package.json package-lock.json

      - name: 7. Mengirim Hasil ke branch hasil-ryan
        run: |
          git config --global user.name "Robot Ryan"
          git config --global user.email "robot@matchlivepro.com"
          git checkout -B hasil-ryan
          git add .
          git commit -m "Auto-minify HTML, CSS, & JS selesai" || echo "Tidak ada perubahan"
          git push -f origin hasil-ryan
